/**
 * Generate every brand asset in brand/ from the geometry, and keep the app's
 * favicon in sync with it.
 *
 *   bun run scripts/brand/build.ts            # write brand/ + patch index.html
 *   bun run scripts/brand/build.ts --check    # fail if anything is stale (CI)
 *
 * SVGs need nothing but bun. The two PNGs (social preview, apple touch icon)
 * are rasterised with headless Chrome, the same binary scripts/capture-app.ts
 * already depends on; without it the SVGs still regenerate and the PNGs are
 * left alone, with a warning, so this never becomes a hard dependency of the
 * gate on a machine that has no browser.
 */

import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

import { faviconDataUri, faviconSvg, lanternSvg, lockupSvg, markFacets, markSvg, PALETTE } from "./mark";
import { GLYPHS, METRICS, UPEM } from "./wordmark-data";

const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const ROOT = join(import.meta.dir, "../..");
const BRAND = join(ROOT, "brand");
const INDEX_HTML = join(ROOT, "web/ui/index.html");
const GEIST_WOFF2 = join(
  ROOT,
  "web/ui/node_modules/@fontsource-variable/geist/files/geist-latin-wght-normal.woff2",
);

/** Social preview: GitHub renders it at 1280×640; we ship exactly that, at 2×. */
const OG = { width: 1280, height: 640, scale: 2 } as const;
/** iOS home screen. Opaque plate — iOS masks the corners itself, and a
 *  transparent icon there comes out as a black square. */
const TOUCH_ICON = 180;

const checkOnly = process.argv.includes("--check");
const stale: string[] = [];

async function emit(path: string, content: string | Uint8Array): Promise<void> {
  const rel = relative(ROOT, path);
  const existing = existsSync(path) ? await readFile(path) : null;
  const next = typeof content === "string" ? Buffer.from(content) : Buffer.from(content);
  if (existing && existing.equals(next)) {
    console.log(`  ok      ${rel}`);
    return;
  }
  if (checkOnly) {
    stale.push(rel);
    console.log(`  STALE   ${rel}`);
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, next);
  console.log(`  ${existing ? "update" : "write "}  ${rel}  (${next.length} bytes)`);
}

// ── SVG assets ──────────────────────────────────────────────────────────────

console.log("brand assets");

const favicon = faviconSvg();
await emit(join(BRAND, "favicon.svg"), favicon);

// Two forms of one mark: the lantern wherever there are pixels to spend, the
// flat reduction wherever there are not. Same solid, same axis, same light in
// the middle — see the header of mark.ts.
//
// The lantern ships twice because its bloom is ground-dependent: a violet halo
// glows on the void and reads as a printing artifact on white.
await emit(join(BRAND, "wisp-mark.svg"), lanternSvg({ size: 96 }));
await emit(join(BRAND, "wisp-mark-glow.svg"), lanternSvg({ size: 96, bloom: 0.06, id: "gl" }));
await emit(join(BRAND, "wisp-mark-flat.svg"), markSvg({ size: 64 }));

// One lockup per ground. The mark is identical in both — only the wordmark's
// ink changes, because #eaeaee text on white is unreadable and vice versa.
await emit(join(BRAND, "wisp-logo-dark.svg"), lockupSvg({ height: 72, fg: PALETTE.paper, bloom: 0.06, id: "ld" }));
await emit(join(BRAND, "wisp-logo-light.svg"), lockupSvg({ height: 72, fg: PALETTE.inkText, id: "ll" }));

// ── the app's in-header mark ─────────────────────────────────────────────────

/**
 * The app draws the mark at 17–24px in its header and gallery, which is squarely
 * reduction territory — the lantern's translucency and edge tracing fall under a
 * pixel there. Emitting the component from here rather than hand-copying the
 * paths means `bun run brand:check` catches it drifting, the same way it catches
 * a stale favicon.
 *
 * Formatted to match web/ui/.prettierrc (no semicolons, double quotes, 2 spaces)
 * so `bun run lint` stays green without a formatting pass.
 */
const markComponent = `/**
 * The Wisp mark, at the size the app actually draws it.
 *
 * GENERATED by scripts/brand/build.ts — do not edit. Run \`bun run brand\` after
 * changing the generator; \`bun run brand:check\` fails if this file is stale.
 *
 * This is the flat reduction from scripts/brand/mark.ts, not the lantern: below
 * roughly 24px the lantern's translucency and luminous edges fall under a pixel
 * and turn to noise. Fills are literal because the mark is violet by definition
 * — it does not inherit \`currentColor\`.
 */
export function WispMark({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" aria-hidden className={className}>
${markFacets({ size: 24, precision: 2 })
  .map((f) => `      <path d="${f.d}" fill="${f.fill}" />`)
  .join("\n")}
    </svg>
  )
}
`;
await emit(join(ROOT, "web/ui/src/components/wisp-mark.tsx"), markComponent);

// ── the app's favicon, inlined ───────────────────────────────────────────────

const START = "    <!-- brand:favicon — generated by scripts/brand/build.ts, do not hand-edit -->";
const END = "    <!-- /brand:favicon -->";

const html = await readFile(INDEX_HTML, "utf8");
const block = [
  START,
  `    <link rel="icon" type="image/svg+xml" href="${faviconDataUri(favicon)}" />`,
  `    <meta name="theme-color" content="${PALETTE.ink}" />`,
  END,
].join("\n");

const from = html.indexOf(START);
const to = html.indexOf(END);
let patched: string;
if (from !== -1 && to !== -1) {
  patched = html.slice(0, from) + block + html.slice(to + END.length);
} else {
  // first run: drop the block in right after the viewport meta
  const anchor = html.indexOf("\n", html.indexOf('name="viewport"'));
  if (anchor === -1) throw new Error("web/ui/index.html: no viewport meta to anchor the favicon to");
  patched = `${html.slice(0, anchor)}\n${block}${html.slice(anchor)}`;
}
await emit(INDEX_HTML, patched);

// ── PNG assets ──────────────────────────────────────────────────────────────

if (!existsSync(CHROME)) {
  console.log(`  skip    brand/*.png — no Chrome at ${CHROME}`);
} else {
  const woff2 = await readFile(GEIST_WOFF2);
  const fontFace = `@font-face{font-family:'Geist';src:url(data:font/woff2;base64,${woff2.toString("base64")}) format('woff2');font-weight:100 900;font-display:block}`;

  /** Render an HTML string to a PNG with headless Chrome. */
  async function shoot(html: string, out: string, width: number, height: number, scale: number) {
    const tmp = join(BRAND, ".render.html");
    await writeFile(tmp, html);
    const png = join(BRAND, ".render.png");
    await rm(png, { force: true });
    const proc = Bun.spawn(
      [
        CHROME,
        "--headless",
        "--disable-gpu",
        "--hide-scrollbars",
        "--default-background-color=00000000",
        `--force-device-scale-factor=${scale}`,
        `--screenshot=${png}`,
        `--window-size=${width},${height}`,
        `file://${tmp}`,
      ],
      { stdout: "ignore", stderr: "ignore" },
    );
    await proc.exited;
    await rm(tmp, { force: true });
    if (!existsSync(png)) throw new Error(`Chrome produced no PNG for ${out}`);
    const bytes = await readFile(png);
    await rm(png, { force: true });
    await emit(join(BRAND, out), bytes);
  }

  // apple touch icon: the mark inset on an opaque plate
  await shoot(
    `<!doctype html><meta charset="utf-8"><style>
html,body{margin:0;width:${TOUCH_ICON}px;height:${TOUCH_ICON}px;background:${PALETTE.ink};overflow:hidden}
div{display:grid;place-items:center;width:100%;height:100%}
svg{width:${Math.round(TOUCH_ICON * 0.8)}px;height:${Math.round(TOUCH_ICON * 0.8)}px;display:block}
</style><div>${lanternSvg({ size: 128, bloom: 0.055, id: "ti" })}</div>`,
    "apple-touch-icon.png",
    TOUCH_ICON,
    TOUCH_ICON,
    1,
  );

  // Social preview. Sized for the worst case rather than the best: a link
  // unfurled in a feed is often 500px wide, so nothing here is smaller than
  // 17px and the headline carries the whole message on its own.
  const heroMark = lanternSvg({ size: 300, bloom: 0.055, id: "og" });
  const wordmarkOnly = wordmarkSvg(52, PALETTE.paper);
  const dots = (
    [
      ["running", "#AF87F1"],
      ["done", "#57b983"],
      ["needs input", "#ddb055"],
    ] as const
  )
    .map(
      ([label, colour]) =>
        `<span class="state"><i style="background:${colour}"></i>${label}</span>`,
    )
    .join("");

  await shoot(
    `<!doctype html><meta charset="utf-8"><style>
${fontFace}
*{box-sizing:border-box}
html,body{margin:0;width:${OG.width}px;height:${OG.height}px;background:${PALETTE.ink};overflow:hidden;
  font-family:'Geist',ui-sans-serif,system-ui;-webkit-font-smoothing:antialiased}
.sheet{position:relative;width:100%;height:100%;display:grid;grid-template-columns:1fr 520px;align-items:center}
/* one soft violet field behind the solid — the only gradient in the system, and
   it exists because a 1280×640 raster can afford what a 16px favicon cannot */
.glow{position:absolute;right:150px;top:50%;width:640px;height:640px;transform:translateY(-50%);
  background:radial-gradient(circle,rgba(175,135,241,0.20) 0%,rgba(175,135,241,0.07) 42%,rgba(175,135,241,0) 68%)}
.hairline{position:absolute;left:0;right:0;top:0;height:1px;background:linear-gradient(90deg,#AF87F1 0%,#2b2b34 38%,rgba(43,43,52,0) 72%)}
.copy{padding:0 0 0 84px;position:relative;display:flex;flex-direction:column;align-items:flex-start}
.copy svg{display:block}
h1{font-size:48px;line-height:1.1;letter-spacing:-0.026em;font-weight:600;color:${PALETTE.paper};margin:26px 0 0}
h1 em{font-style:normal;color:#a2a2ad}
p{font-size:21px;line-height:1.5;letter-spacing:-0.008em;color:#74747f;margin:18px 0 0;max-width:590px}
/* the footer rides in the flow, not pinned to the bottom edge: pinned, it left
   a dead band across the lower third at feed size */
.rule{width:132px;height:1px;background:#2b2b34;margin:32px 0 0}
.meta{display:flex;gap:24px;align-items:center;margin-top:22px;flex-wrap:wrap}
.state{display:inline-flex;align-items:center;gap:9px;font-size:17px;color:#a2a2ad;letter-spacing:0.002em}
.state i{width:8px;height:8px;border-radius:50%;display:block}
.harnesses{font-size:17px;color:#55555f;letter-spacing:0.002em;margin-top:14px}
.harnesses b{color:#74747f;font-weight:500}
.hero{display:grid;place-items:center;position:relative}
.hero svg{display:block;filter:drop-shadow(0 26px 60px rgba(0,0,0,0.6))}
</style>
<div class="sheet">
  <div class="hairline"></div>
  <div class="glow"></div>
  <div class="copy">
    ${wordmarkOnly}
    <h1>Every coding agent,<br><em>one daemon.</em></h1>
    <p>An isolated git worktree per task, and a state machine that cannot lie about it.</p>
    <div class="rule"></div>
    <div class="meta">${dots}</div>
    <div class="harnesses"><b>droid · claude · codex</b> · CLI, web UI, webhooks</div>
  </div>
  <div class="hero">${heroMark}</div>
</div>`,
    "og.png",
    OG.width,
    OG.height,
    OG.scale,
  );
}

/** The wordmark alone, for the social preview's text column. */
function wordmarkSvg(height: number, fill: string): string {
  const scale = height / METRICS.iDotTop;
  const tracking = -0.02 * UPEM * scale;
  const baseline = height;
  let right = 0;
  const parts = GLYPHS.map((g, i) => {
    const x = (g.x * scale) + tracking * i;
    right = Math.max(right, x + g.maxX * scale);
    const point = (px: number, py: number) =>
      `${(x + px * scale).toFixed(2)} ${(baseline - py * scale).toFixed(2)}`;
    return g.d.replace(/([MLQCZ])([^MLQCZ]*)/g, (_m, op: string, rest: string) => {
      if (op === "Z") return "Z";
      const nums = (rest.match(/-?[\d.]+/g) ?? []).map(Number);
      const pairs: string[] = [];
      for (let k = 0; k < nums.length; k += 2) pairs.push(point(nums[k], nums[k + 1]));
      return op + pairs.join(" ");
    });
  });
  const h = baseline - METRICS.descender * scale;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${right.toFixed(2)} ${h.toFixed(2)}" width="${right.toFixed(1)}" height="${h.toFixed(1)}"><path d="${parts.join("")}" fill="${fill}"/></svg>`;
}

if (checkOnly && stale.length > 0) {
  console.error(`\n${stale.length} brand asset(s) stale — run: bun run scripts/brand/build.ts`);
  process.exit(1);
}
console.log("done");
