#!/usr/bin/env bun
// CHANGELOG.md is an index, not a second copy of the release notes. Each
// published version's entry is the summary paragraph its release notes already
// open with (written by a person at release time), its publication date from
// the qualification ledger, and a link to the full notes. Nothing here writes
// prose of its own.
//
// `bun run changelog` regenerates the file; `--check` (inside docs:check)
// refuses a stale one; release:closeout rewrites it once the ledger records a
// publication. A version is listed once it is published: a ledger records its
// publication, or it is a regular release no newer than the newest recorded
// one (0.5.13 shipped without a ledger entry). A release still being prepared
// stays out until its closeout lands. The 0.4 prereleases are not listed: several
// of those candidates never became a GitHub release, and docs/v0.4/ says which.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { compareVersions, isReleaseVersion } from "../shared/release-version";

export interface ChangelogEntry {
  version: string;
  date: string | null;
  summary: string;
  /** repository-relative path of the full release notes */
  notes: string;
}

const HEADER = `# Changelog

Every published Wisp release, newest first. Each entry is the summary from that
release's notes; follow its link for the full notes, upgrade steps and known
limits. This file is generated by \`bun run changelog\`: edit the release notes,
not this file.
`;

const FOOTER = `## Earlier prereleases

The 0.4.0 alpha series was experimental. Its notes, including candidates that
never became a release, are in [docs/v0.4](docs/v0.4/).
`;

export function notesVersion(source: string): string | null {
  const heading = /^# Wisp (\S+)\s*$/m.exec(source);
  return heading && isReleaseVersion(heading[1]!) ? heading[1]! : null;
}

/** The notes' opening paragraph: the lines after the title, up to a blank line, a list or a heading. */
export function notesSummary(source: string): string {
  const lines = source.split("\n");
  const afterTitle = lines.slice(lines.findIndex((line) => line.startsWith("# ")) + 1);
  const paragraph: string[] = [];
  for (const line of afterTitle) {
    if (paragraph.length === 0 && line.trim() === "") continue;
    if (line.trim() === "" || line.startsWith("#") || /^\s*[-*] /.test(line)) break;
    paragraph.push(line.trim());
  }
  return paragraph.join(" ");
}

/** Versions a ledger records as published, and the date each was, when it says. */
export function publications(ledger: string): Map<string, string | null> {
  const published = new Map<string, string | null>();
  for (const match of ledger.matchAll(/^## (\S+) publication\s*$/gm)) published.set(match[1]!, null);
  for (const match of ledger.matchAll(/^## (\S+) publication\s*\n+\*\*Published(?: and promoted)? on (\d{4}-\d{2}-\d{2})\./gm)) {
    published.set(match[1]!, match[2]!);
  }
  return published;
}

export function renderChangelog(entries: readonly ChangelogEntry[]): string {
  const sorted = [...entries].sort((a, b) => compareVersions(b.version, a.version));
  const sections = sorted.map((entry) => {
    const title = entry.date ? `## ${entry.version} (${entry.date})` : `## ${entry.version}`;
    const summary = entry.summary === "" ? "" : `${entry.summary}\n\n`;
    return `${title}\n\n${summary}[Release notes](${entry.notes})\n`;
  });
  return [HEADER, ...sections, FOOTER].join("\n");
}

/** Every published version's entry, read from `docs/v<major>.<minor>/`. */
export function collectEntries(root: string): ChangelogEntry[] {
  const docs = join(root, "docs");
  const lines = readdirSync(docs).filter((name) => /^v\d+\.\d+$/.test(name));
  const published = new Map<string, string | null>();
  for (const line of lines) {
    const ledger = join(docs, line, "QUALIFICATION.md");
    if (existsSync(ledger)) for (const [version, date] of publications(readFileSync(ledger, "utf8"))) published.set(version, date);
  }
  const versions = [...published.keys()].filter(isReleaseVersion);
  if (versions.length === 0) return [];
  const newest = versions.sort(compareVersions).at(-1)!;
  const entries: ChangelogEntry[] = [];
  for (const line of lines) {
    for (const name of readdirSync(join(docs, line)).filter((file) => /^RELEASE-NOTES-.+\.md$/.test(file))) {
      const source = readFileSync(join(docs, line, name), "utf8");
      const version = notesVersion(source);
      if (version === null) continue;
      const regular = !version.includes("-");
      if (!published.has(version) && !(regular && compareVersions(version, newest) <= 0)) continue;
      entries.push({ version, date: published.get(version) ?? null, summary: notesSummary(source), notes: `docs/${line}/${name}` });
    }
  }
  return entries;
}

export function changelogText(root: string): string {
  return renderChangelog(collectEntries(root));
}

/** Rewrites CHANGELOG.md; returns whether it changed. */
export function writeChangelog(root: string): boolean {
  const path = join(root, "CHANGELOG.md");
  const text = changelogText(root);
  if (existsSync(path) && readFileSync(path, "utf8") === text) return false;
  writeFileSync(path, text);
  return true;
}

if (import.meta.main) {
  const root = resolve(import.meta.dir, "..");
  if (process.argv.includes("--check")) {
    const path = join(root, "CHANGELOG.md");
    const current = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (current !== changelogText(root)) {
      console.error("CHANGELOG.md is out of date with the release notes and ledgers: run `bun run changelog`");
      process.exit(1);
    }
    console.log(`checked CHANGELOG.md against ${collectEntries(root).length} published releases`);
  } else {
    console.log(writeChangelog(root) ? "wrote CHANGELOG.md" : "CHANGELOG.md is current");
  }
}
