/**
 * The Wisp mark, at the size the app actually draws it.
 *
 * GENERATED by scripts/brand/build.ts — do not edit. Run `bun run brand` after
 * changing the generator; `bun run brand:check` fails if this file is stale.
 *
 * This is the flat reduction from scripts/brand/mark.ts, not the lantern: below
 * roughly 24px the lantern's translucency and luminous edges fall under a pixel
 * and turn to noise. Fills are literal because the mark is violet by definition
 * — it does not inherit `currentColor`.
 */
export function WispMark({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" aria-hidden className={className}>
      <path d="M10.55 23.40L11.11 19.05L1.40 16.45Z" fill="#2b1651" />
      <path d="M1.40 16.45L6.35 7.70L2.85 5.05Z" fill="#774ac8" />
      <path d="M21.15 18.95L11.11 19.05L10.55 23.40Z" fill="#2b1651" />
      <path d="M2.85 5.05L6.35 7.70L13.45 0.60Z" fill="#956bde" />
      <path d="M22.60 7.55L18.55 9.25L21.15 18.95Z" fill="#2b1651" />
      <path d="M13.45 0.60L18.55 9.25L22.60 7.55Z" fill="#4d2a8c" />
      <path d="M1.40 16.45L11.11 19.05L6.35 7.70Z" fill="#7548c6" />
      <path d="M18.55 9.25L11.11 19.05L21.15 18.95Z" fill="#361b67" />
      <path d="M6.35 7.70L18.55 9.25L13.45 0.60Z" fill="#a57dea" />
      <path d="M6.35 7.70L11.11 19.05L18.55 9.25Z" fill="#b893f3" />
    </svg>
  )
}
