/**
 * The Wisp mark, at the size the app actually draws it.
 *
 * GENERATED by scripts/brand/build.ts — do not edit. Run `bun run brand` after
 * changing the generator; `bun run brand:check` fails if this file is stale.
 *
 * This is S1 flat from scripts/brand/mark.ts, not the 3D spirit: below 64px the
 * 3D turns to a glowing blob. Fills are literal because the mark is violet by
 * definition — it does not inherit `currentColor`.
 */
export function WispMark({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" aria-hidden className={className}>
      <path d="M11.76 23.52C7.53 23.52 4.24 20.46 4.24 16C4.24 11.53 7.06 9.18 7.77 5.89C8.24 3.77 7.53 2.13 5.89 0.48C10.82 1.42 13.18 4.71 13.18 8.71C14.35 8 15.76 7.3 17.17 6.12C18.82 9.18 19.76 12.24 19.76 16C19.76 20.23 16.23 23.52 11.76 23.52Z" fill="#976ddf" />
      <path d="M8.8 14.48C8.8 13.88 9.29 13.4 9.88 13.4C10.48 13.4 10.97 13.88 10.97 14.48L10.97 16.1C10.97 16.7 10.48 17.18 9.88 17.18C9.29 17.18 8.8 16.7 8.8 16.1ZM13.27 14.48C13.27 13.88 13.75 13.4 14.35 13.4C14.95 13.4 15.43 13.88 15.43 14.48L15.43 16.1C15.43 16.7 14.95 17.18 14.35 17.18C13.75 17.18 13.27 16.7 13.27 16.1Z" fill="#120d1c" />
    </svg>
  )
}
